[connections.supabase]
url = "https://thoqlquxaemyyhmpiwzt.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRob3FscXV4YWVteXlobXBpd3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNDUzMzgsImV4cCI6MjA1NDYyMTMzOH0.OUPHc37SgIvAfF32xPkulSYF2CGc3hJSADuLKgT9Zvo"