name: Collect Flood Data

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  
  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests supabase python-dotenv
      
      - name: Run data collection
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python collect_data.py
